#!/usr/bin/env python

import argparse
import sys
import json
import yaml


def get_params(config_file):
    file_stream = open(config_file, 'r')
    params = yaml.load(file_stream)
    return params


def main(filename="random", verbose=False):
    dest = "scenarios/%s-scenario.json" % filename

    scenario_params = get_params('config/scenarios.yaml')[filename]
    products = get_params('config/products.yaml')
    client_params = get_params('config/customers.yaml')

    bakeries_qty = scenario_params['meta']['bakeries']
    clients_qty = sum(scenario_params['meta']['customers'].values())
    grid = scenario_params['street_network']['grid_size']
    days = scenario_params['meta']['days']



if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Creates a random scenario')

    parser.add_argument('--name',
                        nargs=1,
                        help='The scenario name.')
    parser.add_argument('--verbose',
                        action='store_true',
                        default=False,
                        help='Show the details of the scenario while they are\
                              created')
    args = parser.parse_args(sys.argv[1:])
    try:
        main(verbose=args.verbose)
    except ValueError as vae:
        parser.error(str(vae))
