1: # Clients who order some one day in advance and/or same day delivery
  - King's Landing Shop
  - Dorne Supermarket
  - Braavos Cafe
  - Meeren Boulangerie
  - Casterly Rock Cookie Palace
  - The Vale Coffee Shop
  - Iron Island's Bagel Shop
  - Doughnuts of Myr
  - Baelor's Cookie Tower
  - Flea Bottom's Pie Shop
  # - Deli
  # - Market
  # - Store
  # - Emporium
  # - Groceries
  # - Kiosk
  # - Bake Shop
  # - Patisserie
  # - Pastry Shop
2: # Clients who order once a day, one day in advance
  - Winterfell Retirement Home
  - Old Town Hospital
  - Sunspear Canteen
  - Storm's End Diner
  - The Riverland Inn
  - Penthos Hotel
  - Volantis Food Court
  - Castle Black Pub
  - Direwolf Tavern
  - Dragon Bar
3: # Clients who order more than one day in advance
  - Westeros Catering
  - Lannisport Club
  - Eyrie Verein
  - Harrenhal Association
  - Highgarden Hall
  - Dragonstone Events
  - Red Keep Catering
  - The Crow Saloon
  - Black Kinght's Guild
  - Wildfire Alchemist Society
  # - Ballroom
  # - Dining Hall
  # - Gallery
