# The product list will be shuffled randomly for the bakeries
# TODO shuffle the products when ordering
- Bagel
- Bread
- Donut
- Berliner
- Muffin
- Croissant
- Baguette
- Bun
- Ciabatta
- Multigrain Bread
- Brezel
- Cookie
